/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

/**
 *
 * @author Unicomfacauca
 */
import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Test Value Object.
  * This class is value object representing database table TEST
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Test implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ENTERO;
    private String CADENA;
    private String FECHA;
    private double REAL;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Test () {

    }

    public Test (int ENTEROIn) {

          this.ENTERO = ENTEROIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getENTERO() {
          return this.ENTERO;
    }
    public void setENTERO(int ENTEROIn) {
          this.ENTERO = ENTEROIn;
    }

    public String getCADENA() {
          return this.CADENA;
    }
    public void setCADENA(String CADENAIn) {
          this.CADENA = CADENAIn;
    }

    public String getFECHA() {
          return this.FECHA;
    }
    public void setFECHA(String FECHAIn) {
          this.FECHA = FECHAIn;
    }

    public double getREAL() {
          return this.REAL;
    }
    public void setREAL(double REALIn) {
          this.REAL = REALIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ENTEROIn,
          String CADENAIn,
          String FECHAIn,
          double REALIn) {
          this.ENTERO = ENTEROIn;
          this.CADENA = CADENAIn;
          this.FECHA = FECHAIn;
          this.REAL = REALIn;
    }


    /** 
     * hasEqualMapping-method will compare two Test instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Test valueObject) {

          if (valueObject.getENTERO() != this.ENTERO) {
                    return(false);
          }
          if (this.CADENA == null) {
                    if (valueObject.getCADENA() != null)
                           return(false);
          } else if (!this.CADENA.equals(valueObject.getCADENA())) {
                    return(false);
          }
          if (this.FECHA == null) {
                    if (valueObject.getFECHA() != null)
                           return(false);
          } else if (!this.FECHA.equals(valueObject.getFECHA())) {
                    return(false);
          }
          if (valueObject.getREAL() != this.REAL) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Test, mapping to table TEST\n");
        out.append("Persistent attributes: \n"); 
        out.append("ENTERO = " + this.ENTERO + "\n"); 
        out.append("CADENA = " + this.CADENA + "\n"); 
        out.append("FECHA = " + this.FECHA + "\n"); 
        out.append("REAL = " + this.REAL + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Test cloned = new Test();

        cloned.setENTERO(this.ENTERO); 
        if (this.CADENA != null)
             cloned.setCADENA(new String(this.CADENA)); 
        if (this.FECHA != null)
             cloned.setFECHA(new String(this.FECHA)); 
        cloned.setREAL(this.REAL); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
